name: 🤖 Android Builds
'on':
- push
- pull_request
env:
  GODOT_BASE_BRANCH: "4.0"
  SCONSFLAGS: verbose=yes warnings=extra debug_symbols=no module_text_server_fb_enabled=yes
concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-android
  cancel-in-progress: true
jobs:
  android-template:
    runs-on: ubuntu-20.04
    name: Template (target=release, tools=no)
    steps:
    - name: Checkout Godot
      uses: actions/checkout@v2
      with:
        repository: godotengine/godot
        ref: ${{ env.GODOT_BASE_BRANCH }}
    - name: Checkout ECMAScript
      uses: actions/checkout@v2
      with:
        path: ${{github.workspace}}/modules/javascript/
    - name: Make apt sources.list use the default Ubuntu repositories
      run: |
        # sudo rm -f /etc/apt/sources.list.d/*
        # sudo cp -f misc/ci/sources.list /etc/apt/sources.list
        sudo apt-get update
    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Godot build cache
      uses: ./.github/actions/godot-cache
      continue-on-error: true
    - name: Setup python and scons
      uses: ./modules/javascript/.github/actions/godot-deps
      with:
        shell: sh
    - name: Compilation (armv7)
      uses: ./modules/javascript/.github/actions/godot-build
      with:
        sconsflags: ${{ env.SCONSFLAGS }} android_arch=armv7
        platform: android
        target: template_release
        tools: false
        shell: sh
    - name: Compilation (arm64v8)
      uses: ./modules/javascript/.github/actions/godot-build
      with:
        sconsflags: ${{ env.SCONSFLAGS }} android_arch=arm64v8
        platform: android
        target: template_release
        tools: false
        shell: sh
    - name: Generate Godot templates
      run: |
        cd platform/android/java
        ./gradlew generateGodotTemplates
        cd ../../..
        ls -l bin/
    - name: Upload artifact
      uses: ./.github/actions/upload-artifact
