name: 🔗 GHA
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-runner
  cancel-in-progress: true

jobs:
  # First stage: Only static checks, fast and prevent expensive builds from running.

  static-checks:
    if: ${{ vars.DISABLE_GODOT_CI == '' }}
    name: 📊 Static checks
    uses: ./.github/workflows/static_checks.yml

  # Second stage: Run all the builds and some of the tests.

  android-build:
    if: ${{ vars.DISABLE_GODOT_CI == '' }}
    name: 🤖 Android
    needs: static-checks
    uses: ./.github/workflows/android_builds.yml

  ios-build:
    if: ${{ vars.DISABLE_GODOT_CI == '' }}
    name: 🍏 iOS
    needs: static-checks
    uses: ./.github/workflows/ios_builds.yml

  linux-build:
    if: ${{ vars.DISABLE_GODOT_CI == '' }}
    name: 🐧 Linux
    needs: static-checks
    uses: ./.github/workflows/linux_builds.yml

  macos-build:
    if: ${{ vars.DISABLE_GODOT_CI == '' }}
    name: 🍎 macOS
    needs: static-checks
    uses: ./.github/workflows/macos_builds.yml

  windows-build:
    if: ${{ vars.DISABLE_GODOT_CI == '' }}
    name: 🏁 Windows
    needs: static-checks
    uses: ./.github/workflows/windows_builds.yml

  web-build:
    if: ${{ vars.DISABLE_GODOT_CI == '' }}
    name: 🌐 Web
    needs: static-checks
    uses: ./.github/workflows/web_builds.yml

  # Third stage: Run auxiliary tests using build artifacts from previous jobs.

  # Can be turned off for PRs that intentionally break compat with godot-cpp,
  # until both the upstream PR and the matching godot-cpp changes are merged.
  godot-cpp-test:
    if: ${{ vars.DISABLE_GODOT_CI == '' }}
    name: 🪲 Godot CPP
    # This can be changed to depend on another platform, if we decide to use it for
    # godot-cpp instead. Make sure to move the .github/actions/godot-api-dump step
    # appropriately.
    needs: linux-build
    uses: ./.github/workflows/godot_cpp_test.yml

  release:
    needs: godot-cpp-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/groups-4.2')
    
    steps:
      - name: Download android-template artifact
        uses: actions/download-artifact@v2
        with:
          name: android-template
          path: ./artifacts/android-template

      - name: Download godot-api-dump artifact
        uses: actions/download-artifact@v2
        with:
          name: godot-api-dump
          path: ./artifacts/godot-api-dump

      - name: Download ios-template artifact
        uses: actions/download-artifact@v2
        with:
          name: ios-template
          path: ./artifacts/ios-template

      - name: Download linux-editor-mono artifact
        uses: actions/download-artifact@v2
        with:
          name: linux-editor-mono
          path: ./artifacts/linux-editor-mono

      - name: Download linux-template-minimal artifact
        uses: actions/download-artifact@v2
        with:
          name: linux-template-minimal
          path: ./artifacts/linux-template-minimal

      - name: Download linux-template-mono artifact
        uses: actions/download-artifact@v2
        with:
          name: linux-template-mono
          path: ./artifacts/linux-template-mono

      - name: Download macos-editor artifact
        uses: actions/download-artifact@v2
        with:
          name: macos-editor
          path: ./artifacts/macos-editor

      - name: Download macos-template artifact
        uses: actions/download-artifact@v2
        with:
          name: macos-template
          path: ./artifacts/macos-template

      - name: Download web-template artifact
        uses: actions/download-artifact@v2
        with:
          name: web-template
          path: ./artifacts/web-template

      - name: Download windows-editor artifact
        uses: actions/download-artifact@v2
        with:
          name: windows-editor
          path: ./artifacts/windows-editor

      - name: Download windows-template artifact
        uses: actions/download-artifact@v2
        with:
          name: windows-template
          path: ./artifacts/windows-template

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/groups-4.2')
        with:
          files: |
            ./artifacts/android-template/android-template.zip
            ./artifacts/godot-api-dump/godot-api-dump.zip
            ./artifacts/ios-template/ios-template.zip
            ./artifacts/linux-editor-mono/linux-editor-mono.zip
            ./artifacts/linux-template-minimal/linux-template-minimal.zip
            ./artifacts/linux-template-mono/linux-template-mono.zip
            ./artifacts/macos-editor/macos-editor.zip
            ./artifacts/macos-template/macos-template.zip
            ./artifacts/web-template/web-template.zip
            ./artifacts/windows-editor/windows-editor.zip
            ./artifacts/windows-template/windows-template.zip
          body: "This is a https://github.com/V-Sekai/godot release"
          generate_release_notes: true
          append_body: true
